name: Update README

# Trigger the workflow on push to the main branch or on a daily schedule at 9:00 AM UTC
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4

    # Run the Python script to update the README.md file
    - name: Run update script
      run: python update_readme.py

    # Configure Git settings
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    # Reset Git to prevent any conflicts during the push
    - name: Reset Git to prevent conflicts
      run: |
        git checkout main
        git reset --hard HEAD

    # Add and commit changes, if any
    - name: Commit changes
      run: |
        git add README.md
        git commit -m "Automated update of README.md" || echo "No changes to commit"

    # Push changes to the remote repository
    - name: Push changes
      run: |
        git push origin main
